name: Twitter Auto Poster Cron

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-twitter-poster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests gspread google-auth pytz tweepy

      - name: Run Scheduler Worker for X
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCP_CREDS_BASE64: ${{ secrets.GCP_CREDS_BASE64 }}
        run: |
          python worker_x.py
